apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jdupont-role
  namespace: production
rules:

- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups: ["apps"]
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups: ["apps"]
  resources:
  - statefulsets
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups: ["batch"]
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
